title: "Ali Chaudry Portfolio"
description: "Showcasing my projects, experience, and skills in embedded systems, hardware, and software engineering."
url: "https://ali_chaudry_portfolio.github.io"  # Replace with your GitHub username
baseurl: ""  # Leave this empty for GitHub Pages

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Theme Skin (Choose from: air, contrast, dark, dirt, mint, sunrise, aqua, neon, plum)
minimal_mistakes_skin: dark

# Navigation Links
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/
  - title: "Contact"
    url: /contact/

# Author Info
author:
  name: "Ali Chaudry"
  avatar: "/assets/images/profile_pic.png"  # Upload your profile image here
  bio: "Aspiring Embedded Software Engineer | Computer Engineering Student at UIUC"
  location: "Chicago, IL"
  email: "alirc0320@gmail.com"
  linkedin: "https://www.linkedin.com/in/ali-chaudry/"
