# Site Settings
title: "Ali Chaudry Portfolio"
description: "My projects, experience, and contact information."
url: "https://ali_chaudry_portfolio.github.io"  # Replace with your GitHub Pages URL
baseurl: ""  # Leave blank for root deployment

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: dark  # You can try other skins: air, contrast, mint, etc.

# Author Information
author:
  name: "Ali Chaudry"
  avatar: "/assets/images/profile_pic.png"
  bio: "Aspiring Embedded Software Engineer | Computer Engineering Student at UIUC"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Navigation Bar
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

# Show Downloads Button
show_downloads: true
